### ISSUE TITLE
Failed in populateValues() when operating on /etc/laptop-mode/conf.d/board-specific

### ISSUE THREAD

**Issue by murray** [rickysarraf/laptop-mode-tools#178] opened 2022-03-01 18:19 UTC
**Describe the bug**
When I try applying settings using the GUI I get the following error:

_Couldn't apply all requested settings_

In terminal:

_Failed in populateValues() when operating on /etc/laptop-mode/conf.d/board-specific
Couldn't apply setting for checkBox_board-specific_

This happens whether or not "Enable module board-specific" is checked.

**To Reproduce**
Open Laptop Mode Tools
Click 'OK'

**Expected behavior**
It applies the settings without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/6967811/156226516-669bafa7-1875-4e90-853b-48e297c6aba0.png)

**Important Information:**
 - Distribution: Debian 11.2.0
 - Linux Kernel: 5.10.0-11-amd64
 - Laptop Mode Tools version: 1.74-1.1
 - Desktop Environment, if any: GNOME
 - Relevant System Logs: None
 - Laptop Mode Tools verbose logs: As shown

**Additional context**
None

**Comment by murray** [comment] 2022-03-01 18:41
Removing the directory /etc/laptop-mode/conf.d/board-specific resolved the issue. It only contained a README file.

**Comment by rickysarraf** [comment] 2022-03-02 09:02
Again, Thanks for reporting. Since this is a duplicate of #177 I'm closing this in favor of that one. Let's continue it on that bug report.

**Closed as completed by rickysarraf** 2022-03-02 09:02 UTC
